### ISSUE TITLE
Add --exclude flag to pull command similar to rsync

### ISSUE THREAD

**Issue by Mokubyow** [scribd/objinsync#1]
There are cases when it could be beneficial to sync multiple directories without deleting certain contents that already exist in the target location. For example, I have a `lib/` directory with custom operators, hooks, etc that needs to be synced in addition to my `dags/` folder and both are under the following location: `s3://<bucket>/airflow/`. Currently, if I were to run the pull command: `objinsync pull s3://<bucket>/airflow/ ${AIRFLOW_HOME}/` I would delete other important files such as my `airflow.cfg` file. Therefore it could be nice to implement an `--exclude` flag that would preserve files or directories in the target location so the pull command could be used to directories with other files present. 

Final command might look something like this:
`objinsync pull s3://<bucket>/airflow/ ${AIRFLOW_HOME}/ --exclude "airflow.cfg" --exclude "some_dir/*"`

**Comment by houqp** [comment]
added a new --exclude option, to ignore a whole directory, you need to use doublestar: `--exclude 'some_dir/**'`
