### ISSUE TITLE
Publish to Docker Registry with GitHub workflow

### ISSUE THREAD

**Issue by ron-damon** [scribd/objinsync#12]
Thanks for the tool, it's really useful!

It would be great to publish to docker Registry using the existent GitHub workflow, tagging the image with the specific release version `v#.#.#` and `latest`.

**Comment by ext-mamonast** [comment]
@houqp not wanting to look "pushy" here, and really thankful for your work :) 

Just wanted to check if you have had the chance to the details with the IT team and see if there something we might help from our end, to maybe to ease your load.

**Comment by houqp** [comment]
Sorry for the delay, I followed up on the internal ticket, let's see our IT team can help prioritize it this time.

**Comment by houqp** [comment]
public images are now available under https://github.com/orgs/scribd/packages/container/package/objinsync

**Comment by mekza** [comment]
@houqp maybe we could re-open this issue since, images are not available anymore?

**Comment by houqp** [comment]
@mekza sorry, i missed your message, let me file an internal ticket to investigate this.

**Comment by houqp** [comment]
@mekza could you give it another try? We have fixed the visibility for the package.
