### ISSUE TITLE
Pulled files are empty

### ISSUE THREAD

**Issue by liorrozen** [scribd/objinsync#7]
Hi! Thanks for this tool! It looks like its exactly what I need! I'm having some issues using it though: 

Any file I pull is created as an empty (0 byte) file.

I have an s3 bucket called `my-bucket` which holds two files: `foo.txt` and `image.png`.
When I run a pull command the files get created but they are both empty:

```
root@gosand:/tmp# ls -l /tmp
total 0
root@gosand:/tmp# objinsync pull --once s3://my-bucket/git /tmp
{"level":"info","ts":1595423591.3152442,"caller":"objinsync/main.go:86","msg":"SENTRY_DSN not found, sentry integration disabled."}
{"level":"info","ts":1595423591.3153822,"caller":"objinsync/main.go:141","msg":"Pulling from s3://my-bucket/git to /tmp..."}
{"level":"info","ts":1595423591.3154054,"caller":"objinsync/main.go:125","msg":"Pull started."}
{"level":"info","ts":1595423591.317076,"caller":"sync/pull.go:357","msg":"Listing objects","bucket":"my-bucket","dirpath":"git"}
{"level":"info","ts":1595423591.393758,"caller":"sync/pull.go:203","msg":"Object list page contains 3 objects."}
{"level":"info","ts":1595423591.423097,"caller":"objinsync/main.go:137","msg":"Pull finished in 107.686584ms seconds."}
root@gosand:/tmp# ls -l /tmp
total 0
-rw-r--r-- 1 root root 0 Jul 22 13:13 foo.txt
-rw-r--r-- 1 root root 0 Jul 22 13:13 image.png
```

- I'm running `objinsync` on a container based off `golang:1.14`.
- I've tried using a prebuilt binary (v2.3.0) and also using `go get`.
- The container is running on an EKS cluster (kubernetes 1.16)
- It receives permissions to access this bucket with the following IAM policy:

 ```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket",
                "arn:aws:s3:::my-bucket/git"
            ]
        }
    ]
}
```

Is there any other info I can provide to help debug this?

**Comment by houqp** [comment]
@liorrozen sorry i missed this notification. I have not seen this before myself. Can you try running it with `DEBUG=1` environment variable to see if you can get more info out of it?

**Comment by liorrozen** [comment]
Hi @houqp, thanks for the response! I can't reproduce this any more... I believe it was a permissions issue on my side.

Thanks again!

**Comment by jonasrla** [comment]
I was getting the same issue. I figured that it's needed to add and *. In this case that you look like this

```
{
   "Version": "2012-10-17",
   "Statement": [
       {
           "Sid": "VisualEditor0",
           "Effect": "Allow",
           "Action": [
               "s3:GetObject",
               "s3:ListBucket"
           ],
           "Resource": [
               "arn:aws:s3:::my-bucket",
               "arn:aws:s3:::my-bucket/git/*"
           ]
       }
   ]
}
```
